### ISSUE TITLE
Run MORe Doesn't Work

### ISSUE THREAD

**Issue by nuralfiekowati** [anaarmas/MORe#1]
Dear developer,

I am currently working with some reasoners for a research. Since I am working with the reasoners for OWL 2, I am trying to run MORe as one of the reasoners. I have already tried to follow the sample of MORe usage that you write, but I have an exception as follows:

Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
	at sun.security.util.SignatureFileVerifier.process(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarFile.initializeVerifier(Unknown Source)
	at java.util.jar.JarFile.ensureInitialization(Unknown Source)
	at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at ontologybasedinconsistencymeasures.inconsistencyMeasureMore.main(inconsistencyMeasureMore.java:57)

The exception points to line 57 in my source codes which is to define the reasoner factory: **MOReReasonerFactory rf = new MOReReasonerFactory();**

Could you please give me an insight how do I solve that exception?

**Comment by k00ni** [comment]
I would like to know that too. Seems like the project is abandoned?
